version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@database:5432/postgres
      - SECRET_KEY=mysecretkey
      - JWT_SECRET_KEY=supersecretkey
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "80:80"  #  Maps Nginx in the container to localhost
    depends_on:
      - backend

volumes:
  postgres_data:
